(deftheme catppuccin-mocha "Catppuccin Mocha theme with refined typography and comprehensive coverage.")
(let* ((bg-main    "#1e1e2e") (bg-surf    "#313244") (bg-overlay "#45475a")
       (bg-border  "#585b70") (fg-main    "#cdd6f4") (fg-dim     "#6c7086")
       (c1         "#f38ba8") (c2         "#89b4fa") (c3         "#f9e2af")
       (c4         "#a6e3a1") (c5         "#cba6f7") (c6         "#94e2d5")
       (c7         "#fab387") (c8         "#89dceb")
       (col-error   c1) (col-warning c3) (col-success c4)
       (col-keyword c5) (col-func    c2) (col-type    c6)
       (col-const   c7) (col-string  c4) (col-comment fg-dim) (col-link c2))
  (custom-theme-set-variables 'catppuccin-mocha '(frame-background-mode (quote dark)))
  (custom-theme-set-faces 'catppuccin-mocha
   `(default ((t (:foreground ,fg-main :background ,bg-main))))
   `(bold ((t (:weight bold :foreground ,fg-main))))
   `(italic ((t (:slant italic))))
   `(bold-italic ((t (:weight bold :slant italic))))
   `(cursor ((t (:background ,c5))))
   `(fringe ((t (:foreground ,fg-dim :background ,bg-main))))
   `(border ((t (:background ,bg-border))))
   `(vertical-border ((t (:foreground ,bg-border))))
   `(window-divider ((t (:foreground ,bg-border))))
   `(scroll-bar ((t (:background ,bg-main :foreground ,bg-border))))
   `(tool-bar ((t (:background ,bg-main :foreground ,fg-main))))
   `(menu ((t (:background ,bg-main :foreground ,fg-main))))
   `(minibuffer-prompt ((t (:foreground ,c6 :weight semi-bold))))
   `(link ((t (:foreground ,col-link :underline t :weight semi-bold))))
   `(link-visited ((t (:foreground ,c5 :underline t :slant italic))))
   `(shadow ((t (:foreground ,fg-dim :weight light))))
   `(match ((t (:foreground ,bg-main :background ,col-warning :weight bold))))
   `(region ((t (:background ,bg-overlay :foreground ,fg-main))))
   `(secondary-selection ((t (:background ,bg-surf))))
   `(trailing-whitespace ((t (:foreground ,bg-main :background ,col-error :weight bold))))
   `(tooltip ((t (:foreground ,fg-main :background ,bg-surf :weight normal))))
   `(mouse ((t (:background ,fg-dim))))
   `(highlight ((t (:background ,bg-overlay))))
   `(success ((t (:foreground ,col-success :weight semi-bold))))
   `(warning ((t (:foreground ,col-warning :weight bold))))
   `(error ((t (:foreground ,col-error :weight bold))))
   `(button ((t (:foreground ,c2 :underline t :weight bold))))
   `(font-lock-builtin-face ((t (:foreground ,col-type :weight semi-bold))))
   `(font-lock-comment-face ((t (:foreground ,col-comment :slant italic :weight light))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,col-comment :slant italic :weight light))))
   `(font-lock-constant-face ((t (:foreground ,col-const :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,c4 :slant italic))))
   `(font-lock-function-name-face ((t (:foreground ,col-func :weight bold :slant italic))))
   `(font-lock-function-call-face ((t (:foreground ,c2 :weight bold))))
   `(font-lock-keyword-face ((t (:foreground ,col-keyword :weight bold))))
   `(font-lock-string-face ((t (:foreground ,col-string))))
   `(font-lock-type-face ((t (:foreground ,col-type :weight semi-bold))))
   `(font-lock-variable-name-face ((t (:foreground ,fg-main))))
   `(font-lock-variable-use-face ((t (:foreground ,fg-main :weight semi-bold))))
   `(font-lock-warning-face ((t (:foreground ,col-warning :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,c2 :weight normal))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,c3))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,c3))))
   `(font-lock-operator-face ((t (:foreground ,c8 :weight bold))))
   `(font-lock-property-name-face ((t (:foreground ,c2 :weight normal))))
   `(font-lock-property-use-face ((t (:foreground ,c2 :weight normal))))
   `(font-lock-number-face ((t (:foreground ,c3 :weight normal))))
   `(font-lock-bracket-face ((t (:foreground ,fg-dim :weight normal))))
   `(font-lock-delimiter-face ((t (:foreground ,fg-dim :weight normal))))
   `(show-paren-match ((t (:background ,bg-overlay :foreground ,c2 :weight bold))))
   `(show-paren-mismatch ((t (:background ,col-error :foreground ,bg-main :weight bold))))
   `(hl-paren-face-0 ((t (:foreground ,c1 :weight bold))))
   `(hl-paren-face-1 ((t (:foreground ,c2 :weight bold))))
   `(hl-paren-face-2 ((t (:foreground ,c3 :weight bold))))
   `(hl-paren-face-3 ((t (:foreground ,c4 :weight bold))))
   `(hl-paren-face-4 ((t (:foreground ,c5 :weight bold))))
   `(hl-paren-face-5 ((t (:foreground ,c6 :weight bold))))
   `(hl-paren-face-6 ((t (:foreground ,c7 :weight bold))))
   `(hl-paren-face-7 ((t (:foreground ,c8 :weight bold))))
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,c1 :weight semi-bold))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,c2 :weight semi-bold))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,c3 :weight semi-bold))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,c4 :weight semi-bold))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,c5 :weight semi-bold))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,c6 :weight semi-bold))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,c7 :weight semi-bold))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,c8 :weight semi-bold))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,c1 :weight semi-bold))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,col-error :weight bold))))
   `(mode-line ((t (:foreground ,fg-main :background ,bg-surf :box nil :weight bold))))
   `(mode-line-inactive ((t (:foreground ,fg-dim :background ,bg-main :box nil :weight light))))
   `(mode-line-buffer-id ((t (:weight extra-bold :foreground ,c1))))
   `(mode-line-highlight ((t (:background ,bg-overlay :weight bold))))
   `(header-line ((t (:foreground ,fg-main :background ,bg-surf :box nil :weight bold))))
   `(tab-bar ((t (:background ,bg-main :foreground ,fg-dim :weight normal))))
   `(tab-bar-tab ((t (:background ,bg-surf :foreground ,c1 :weight bold))))
   `(tab-bar-tab-inactive ((t (:background ,bg-main :foreground ,fg-dim :weight light))))
   `(tab-line ((t (:background ,bg-main :foreground ,fg-dim :weight normal))))
   `(tab-line-tab ((t (:background ,bg-surf :foreground ,c1 :weight bold))))
   `(tab-line-tab-inactive ((t (:background ,bg-main :foreground ,fg-dim :weight light))))
   `(line-number ((t (:foreground ,fg-dim :background ,bg-main :weight light))))
   `(line-number-current-line ((t (:foreground ,c1 :background ,bg-surf :weight bold))))
   `(linum ((t (:inherit line-number))))
   `(whitespace-space ((t (:foreground ,bg-overlay))))
   `(whitespace-tab ((t (:foreground ,bg-overlay :weight bold))))
   `(whitespace-newline ((t (:foreground ,bg-overlay))))
   `(whitespace-trailing ((t (:foreground ,bg-main :background ,col-error :weight bold))))
   `(whitespace-empty ((t (:foreground ,bg-main :background ,col-warning :weight bold))))
   `(whitespace-line ((t (:background ,bg-surf :foreground ,fg-dim))))
   `(highlight-indent-guides-character-face ((t (:foreground ,bg-overlay :weight light))))
   `(hl-todo-face ((t (:foreground ,col-error :weight bold :background ,bg-overlay))))
   `(isearch ((t (:foreground ,bg-main :background ,col-warning :weight extra-bold))))
   `(isearch-fail ((t (:foreground ,bg-main :background ,col-error :weight bold))))
   `(lazy-highlight ((t (:foreground ,fg-main :background ,bg-overlay :weight normal))))
   `(ido-first-match ((t (:foreground ,c3 :weight bold))))
   `(ido-only-match ((t (:foreground ,c4 :weight extra-bold))))
   `(ido-subdir ((t (:foreground ,c4 :weight bold))))
   `(ido-indicator ((t (:foreground ,bg-main :background ,col-error :weight bold))))
   `(ido-virtual ((t (:foreground ,fg-dim :weight light))))
   `(company-tooltip ((t (:foreground ,fg-main :background ,bg-surf :weight normal))))
   `(company-tooltip-selection ((t (:foreground ,bg-main :background ,c1 :weight bold))))
   `(company-tooltip-common ((t (:foreground ,c3 :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,fg-dim :weight light))))
   `(company-scrollbar-fg ((t (:background ,bg-overlay))))
   `(company-scrollbar-bg ((t (:background ,bg-surf))))
   `(corfu-default ((t (:foreground ,fg-main :background ,bg-surf :weight normal))))
   `(corfu-current ((t (:foreground ,bg-main :background ,c1 :weight bold))))
   `(corfu-bar ((t (:background ,c2 :weight bold))))
   `(vertico-current ((t (:foreground ,bg-main :background ,c1 :weight bold))))
   `(vertico-group-title ((t (:foreground ,c4 :weight extra-bold))))
   `(vertico-group-separator ((t (:foreground ,bg-overlay :weight light))))
   `(consult-line-number ((t (:foreground ,c3 :weight bold))))
   `(consult-file ((t (:foreground ,c4 :weight bold))))
   `(marginalia-documentation ((t (:foreground ,fg-dim :slant italic))))
   `(marginalia-mode ((t (:foreground ,c2 :weight semi-bold))))
   `(marginalia-size ((t (:foreground ,c3 :weight normal))))
   `(orderless-match-face-0 ((t (:foreground ,c1 :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,c2 :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,c3 :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,c4 :weight bold))))
   `(which-key-key-face ((t (:foreground ,c4 :weight bold))))
   `(which-key-command-description-face ((t (:foreground ,fg-main :weight normal))))
   `(which-key-group-description-face ((t (:foreground ,c3 :weight semi-bold))))
   `(eldoc-highlight-function-argument ((t (:foreground ,c2 :weight bold :slant italic))))
   `(dired-directory ((t (:foreground ,c4 :weight bold))))
   `(dired-flagged ((t (:foreground ,col-error :weight bold))))
   `(dired-marked ((t (:foreground ,c3 :weight bold))))
   `(dired-symlink ((t (:foreground ,c5 :slant italic :weight normal))))
   `(dired-header ((t (:foreground ,c1 :weight extra-bold))))
   `(dired-ignored ((t (:foreground ,fg-dim :weight light))))
   `(diff-added ((t (:foreground ,c4 :weight semi-bold))))
   `(diff-removed ((t (:foreground ,col-error :weight bold))))
   `(diff-changed ((t (:foreground ,c3 :weight bold))))
   `(diff-header ((t (:background ,bg-surf :foreground ,fg-dim :weight normal))))
   `(diff-file-header ((t (:background ,bg-overlay :foreground ,fg-main :weight bold))))
   `(diff-hunk-header ((t (:background ,bg-overlay :foreground ,c2 :weight semi-bold))))
   `(magit-section-heading ((t (:foreground ,c1 :weight extra-bold))))
   `(magit-section-highlight ((t (:background ,bg-surf :weight normal))))
   `(magit-hunk-heading ((t (:background ,bg-overlay :weight normal))))
   `(magit-hunk-heading-highlight ((t (:background ,bg-overlay :foreground ,fg-main :weight bold))))
   `(magit-diff-context-highlight ((t (:background ,bg-surf :weight light))))
   `(magit-diffstat-added ((t (:foreground ,c4 :weight bold))))
   `(magit-diffstat-removed ((t (:foreground ,col-error :weight bold))))
   `(magit-log-author ((t (:foreground ,c4 :weight semi-bold))))
   `(magit-log-date ((t (:foreground ,fg-dim :weight light))))
   `(magit-branch-local ((t (:foreground ,c4 :weight bold))))
   `(magit-branch-remote ((t (:foreground ,c5 :slant italic :weight normal))))
   `(magit-tag ((t (:foreground ,c3 :weight bold))))
   `(magit-process-ok ((t (:foreground ,c4 :weight bold))))
   `(magit-process-ng ((t (:foreground ,col-error :weight bold))))
   `(diff-hl-insert ((t (:background ,c4 :weight bold))))
   `(diff-hl-delete ((t (:background ,col-error :weight bold))))
   `(diff-hl-change ((t (:background ,c3 :weight bold))))
   `(git-gutter-added ((t (:foreground ,c4 :weight bold))))
   `(git-gutter-deleted ((t (:foreground ,col-error :weight bold))))
   `(git-gutter-modified ((t (:foreground ,c3 :weight bold))))
   `(vc-conflict-state ((t (:background ,col-error :foreground ,bg-main :weight bold))))
   `(vc-edited-state ((t (:foreground ,c3 :weight semi-bold))))
   `(vc-missing-state ((t (:foreground ,col-error :weight bold))))
   `(vc-up-to-date-state ((t (:foreground ,fg-dim :weight light))))
   `(lsp-face-highlight-read ((t (:background ,bg-surf :weight normal))))
   `(lsp-face-highlight-textual ((t (:background ,bg-surf :weight bold))))
   `(lsp-face-highlight-write ((t (:background ,bg-overlay :weight bold))))
   `(lsp-ui-sideline-code-action ((t (:foreground ,c3 :weight bold))))
   `(lsp-ui-sideline-current-symbol ((t (:foreground ,c2 :weight bold :slant italic))))
   `(ts-comment ((t (:foreground ,col-comment :slant italic :weight light))))
   `(ts-constant ((t (:foreground ,col-const :slant italic))))
   `(ts-function ((t (:foreground ,col-func :weight bold :slant italic))))
   `(ts-keyword ((t (:foreground ,col-keyword :weight bold))))
   `(ts-number ((t (:foreground ,c3 :weight normal))))
   `(ts-operator ((t (:foreground ,c8 :weight bold))))
   `(ts-property ((t (:foreground ,c2 :weight normal))))
   `(ts-punctuation-bracket ((t (:foreground ,fg-dim :weight normal))))
   `(ts-string ((t (:foreground ,col-string :weight normal))))
   `(ts-type ((t (:foreground ,col-type :weight semi-bold))))
   `(ts-variable ((t (:foreground ,fg-main :weight normal))))
   `(ts-variable-builtin ((t (:foreground ,col-type :weight semi-bold))))
   `(flycheck-error ((t (:underline (:style wave :color ,col-error) :weight bold))))
   `(flycheck-warning ((t (:underline (:style wave :color ,col-warning) :weight bold))))
   `(flycheck-info ((t (:underline (:style wave :color ,c4) :weight semi-bold))))
   `(flycheck-fringe-error ((t (:foreground ,col-error :weight extra-bold))))
   `(flycheck-fringe-warning ((t (:foreground ,col-warning :weight bold))))
   `(flycheck-fringe-info ((t (:foreground ,c4 :weight bold))))
   `(flymake-error ((t (:underline (:style wave :color ,col-error) :weight bold))))
   `(flymake-warning ((t (:underline (:style wave :color ,col-warning) :weight bold))))
   `(flyspell-incorrect ((t (:underline (:style wave :color ,col-error) :weight bold))))
   `(flyspell-duplicate ((t (:underline (:style wave :color ,col-warning) :weight bold))))
   `(compilation-info ((t (:foreground ,c4 :weight semi-bold))))
   `(compilation-warning ((t (:foreground ,col-warning :weight bold))))
   `(compilation-error ((t (:foreground ,col-error :weight bold))))
   `(compilation-line-number ((t (:foreground ,fg-dim :weight light))))
   `(org-level-1 ((t (:foreground ,c1 :weight extra-bold :height 1.2))))
   `(org-level-2 ((t (:foreground ,c4 :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,c3 :weight semi-bold))))
   `(org-level-4 ((t (:foreground ,fg-main :weight bold))))
   `(org-level-5 ((t (:foreground ,fg-dim :weight normal))))
   `(org-done ((t (:foreground ,c4 :weight bold))))
   `(org-todo ((t (:foreground ,col-error :weight extra-bold))))
   `(org-headline-done ((t (:foreground ,fg-dim :strike-through t :weight light))))
   `(org-code ((t (:foreground ,c3 :background ,bg-surf :weight normal))))
   `(org-verbatim ((t (:foreground ,c4 :background ,bg-surf :slant italic))))
   `(org-block ((t (:background ,bg-surf :weight normal))))
   `(org-block-begin-line ((t (:foreground ,fg-dim :background ,bg-overlay :weight light))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-table ((t (:foreground ,fg-dim :weight light))))
   `(org-link ((t (:foreground ,col-link :underline t :weight semi-bold))))
   `(org-date ((t (:foreground ,c5 :slant italic))))
   `(org-upcoming-deadline ((t (:foreground ,c3 :weight bold))))
   `(org-scheduled-today ((t (:foreground ,c4 :weight bold :slant italic))))
   `(org-deadline ((t (:foreground ,col-error :weight extra-bold))))
   `(org-checkbox ((t (:foreground ,c3 :weight bold))))
   `(org-document-title ((t (:foreground ,c1 :weight ultra-bold :height 1.5))))
   `(org-meta-line ((t (:foreground ,fg-dim :slant italic :weight light))))
   `(org-special-keyword ((t (:foreground ,c3 :weight bold))))
   `(org-tag ((t (:foreground ,c2 :weight semi-bold))))
   `(markdown-header-face-1 ((t (:foreground ,c1 :weight extra-bold :height 1.3))))
   `(markdown-header-face-2 ((t (:foreground ,c4 :weight bold :height 1.2))))
   `(markdown-header-face-3 ((t (:foreground ,c3 :weight semi-bold :height 1.1))))
   `(markdown-header-face-4 ((t (:foreground ,fg-main :weight bold))))
   `(markdown-header-face-5 ((t (:foreground ,fg-dim :weight normal))))
   `(markdown-bold-face ((t (:weight extra-bold))))
   `(markdown-italic-face ((t (:slant italic))))
   `(markdown-link-face ((t (:foreground ,col-link :underline t :weight semi-bold))))
   `(markdown-code-face ((t (:background ,bg-surf :weight normal))))
   `(markdown-inline-code-face ((t (:foreground ,c3 :background ,bg-surf :weight normal))))
   `(markdown-list-face ((t (:foreground ,c1 :weight bold))))
   `(markdown-blockquote-face ((t (:foreground ,fg-dim :slant italic :weight light))))
   `(rst-level-1 ((t (:foreground ,c1 :weight extra-bold))))
   `(rst-level-2 ((t (:foreground ,c4 :weight bold))))
   `(rst-level-3 ((t (:foreground ,c3 :weight semi-bold))))
   `(rst-level-4 ((t (:foreground ,fg-main :weight bold))))
   `(rst-level-5 ((t (:foreground ,fg-dim :weight normal))))
   `(json-key ((t (:foreground ,c1 :weight bold))))
   `(json-string ((t (:foreground ,c5 :slant italic))))
   `(json-number ((t (:foreground ,c3 :weight normal))))
   `(json-null ((t (:foreground ,fg-dim :slant italic))))
   `(json-boolean ((t (:foreground ,c2 :weight semi-bold))))
   `(xml-tag ((t (:foreground ,c1 :weight bold))))
   `(xml-attribute-name ((t (:foreground ,c2 :weight normal))))
   `(xml-attribute-value ((t (:foreground ,c5 :slant italic))))
   `(html-tag-name ((t (:foreground ,c1 :weight bold))))
   `(html-helper-tag-name ((t (:foreground ,c2 :weight normal))))
   `(html-argument-name ((t (:foreground ,c2 :weight normal))))
   `(html-argument-value ((t (:foreground ,c5 :slant italic))))
   `(css-property ((t (:foreground ,c2 :weight semi-bold))))
   `(css-selector ((t (:foreground ,c1 :weight bold))))
   `(css-string ((t (:foreground ,c5 :slant italic))))
   `(css-color ((t (:foreground ,c3 :weight normal))))
   `(term-color-black ((t (:foreground ,bg-overlay :background ,bg-overlay))))
   `(term-color-red ((t (:foreground ,col-error :background ,col-error :weight bold))))
   `(term-color-green ((t (:foreground ,c4 :background ,c4 :weight bold))))
   `(term-color-yellow ((t (:foreground ,c3 :background ,c3 :weight bold))))
   `(term-color-blue ((t (:foreground ,c2 :background ,c2 :weight bold))))
   `(term-color-magenta ((t (:foreground ,c1 :background ,c1 :weight bold))))
   `(term-color-cyan ((t (:foreground ,c4 :background ,c4 :weight bold))))
   `(term-color-white ((t (:foreground ,fg-main :background ,fg-main :weight bold))))
   `(eshell-prompt ((t (:foreground ,c1 :weight extra-bold))))
   `(eshell-ls-directory ((t (:foreground ,c4 :weight bold))))
   `(eshell-ls-executable ((t (:foreground ,c4 :weight bold))))
   `(eshell-ls-symlink ((t (:foreground ,c5 :slant italic))))
   `(eshell-ls-archive ((t (:foreground ,c3 :weight semi-bold))))
   `(eshell-ls-clutter ((t (:foreground ,col-error :weight bold))))
   `(eshell-ls-missing ((t (:foreground ,col-error :weight bold))))
   `(eshell-ls-readonly ((t (:foreground ,c3 :weight normal))))
   `(eshell-ls-special ((t (:foreground ,c1 :weight bold))))
   `(shell-option-switch ((t (:foreground ,c2 :weight normal))))
   `(info-header-node ((t (:foreground ,c4 :weight bold))))
   `(info-xref ((t (:foreground ,col-link :underline t :weight semi-bold))))
   `(info-title-1 ((t (:foreground ,c1 :weight extra-bold))))
   `(info-title-2 ((t (:foreground ,c4 :weight bold))))
   `(info-title-3 ((t (:foreground ,c3 :weight semi-bold))))
   `(message-header-name ((t (:foreground ,c2 :weight semi-bold))))
   `(message-header-subject ((t (:foreground ,c1 :weight bold))))
   `(message-header-to ((t (:foreground ,fg-main :weight normal))))
   `(message-cited-text ((t (:foreground ,fg-dim :slant italic :weight light))))
   `(calendar-today ((t (:background ,bg-overlay :foreground ,c3 :weight bold))))
   `(diary ((t (:foreground ,c1 :weight semi-bold))))
   `(holiday ((t (:foreground ,c4 :weight bold))))
   `(widget-button ((t (:foreground ,c1 :weight bold))))
   `(widget-field ((t (:background ,bg-surf :foreground ,fg-main :weight normal))))
   `(custom-state ((t (:foreground ,c4 :weight semi-bold))))
   `(custom-group-tag ((t (:foreground ,c1 :weight extra-bold :height 1.1))))
   `(custom-group-tag-1 ((t (:foreground ,c4 :weight bold))))
   `(help-argument-name ((t (:foreground ,c2 :slant italic))))
   `(Man-overstrike ((t (:foreground ,c1 :weight extra-bold))))
   `(Man-underline ((t (:foreground ,c4 :underline t :weight bold))))
   `(package-name ((t (:foreground ,c4 :weight bold))))
   `(package-status-available ((t (:foreground ,c4 :weight normal))))
   `(package-status-installed ((t (:foreground ,c4 :weight semi-bold))))
   `(tabulated-list-header ((t (:background ,bg-surf :weight extra-bold))))
   `(process-menu-buffer ((t (:foreground ,c4 :weight semi-bold))))
   `(battery-mode-line-low ((t (:foreground ,col-error :weight bold))))
   `(battery-mode-line-charging ((t (:foreground ,c4 :weight bold))))
   `(powerline-active1 ((t (:background ,bg-surf :foreground ,fg-main :weight bold))))
   `(powerline-active2 ((t (:background ,bg-overlay :foreground ,fg-main :weight normal))))
   `(powerline-inactive1 ((t (:background ,bg-main :foreground ,fg-dim :weight light))))))
(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(provide-theme 'catppuccin-mocha)
